# Generated by Django 5.1.6 on 2025-02-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('category', models.CharField(blank=True, choices=[('calf', 'Calf'), ('milking_cow', 'Milking Cow'), ('bull', 'Bull')], max_length=20)),
                ('health_status', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
