# Generated by Django 5.1.6 on 2025-02-20 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Liters of milk produced', max_digits=5)),
                ('cow', models.ForeignKey(limit_choices_to={'category': 'milking'}, on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
            ],
        ),
    ]
