# Generated by Django 5.1.6 on 2025-02-20 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_milkrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecord',
            name='cow',
            field=models.ForeignKey(limit_choices_to={'category': 'milking_cow'}, on_delete=django.db.models.deletion.CASCADE, to='animals.animal'),
        ),
    ]
