# Generated by Django 5.1.6 on 2025-03-26 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_milkrecord_cow'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalImmunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_immunized', models.BooleanField(default=False)),
                ('immunization_date', models.DateField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
            ],
        ),
    ]
