# Generated by Django 5.1.6 on 2025-02-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('calf', 'Calf'), ('milking_cow', 'Milking Cow'), ('bull', 'Bull')], max_length=20)),
                ('quantity_per_animal', models.DecimalField(decimal_places=2, help_text='Quantity of feed per animal per day (kg or liters)', max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
