# Generated by Django 5.1.6 on 2025-02-23 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0003_alter_milkrecord_cow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmunizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('applicable_category', models.CharField(choices=[('calf', 'Calf'), ('milking_cow', 'Milking Cow'), ('bull', 'Bull')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ImmunizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_administered', models.DateField()),
                ('immunized', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
                ('immunization_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immunization.immunizationtype')),
            ],
        ),
    ]
