# Generated by Django 5.1.6 on 2025-02-24 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immunization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmunizationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('calf', 'Calf'), ('milking_cow', 'Milking Cow'), ('bull', 'Bull')], max_length=50)),
                ('min_age_months', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='immunizationrecord',
            name='immunization_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immunization.immunizationschedule'),
        ),
        migrations.DeleteModel(
            name='ImmunizationType',
        ),
    ]
