# Generated by Django 5.1.6 on 2025-02-24 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immunization', '0002_immunizationschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmunizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('applicable_category', models.CharField(max_length=255)),
                ('eligibility_period', models.IntegerField(help_text='Age in months when immunization is required')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='immunizationrecord',
            name='date_administered',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='immunizationrecord',
            name='immunization_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immunization.immunizationtype'),
        ),
        migrations.DeleteModel(
            name='ImmunizationSchedule',
        ),
    ]
