# Generated by Django 5.1.6 on 2025-02-26 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immunization', '0003_immunizationtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immunization_name', models.CharField(max_length=100)),
                ('applicable_category', models.CharField(choices=[('calf', 'Calf'), ('milking_cow', 'Milking Cow'), ('bull', 'Bull')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_administered', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='immunizationrecord',
            name='date_administered',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='immunizationrecord',
            name='immunization_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immunization.immunization'),
        ),
        migrations.DeleteModel(
            name='ImmunizationType',
        ),
    ]
