# Generated by Django 5.1.6 on 2025-02-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immunization', '0004_immunization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immunization',
            old_name='applicable_category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='immunization',
            name='date_administered',
        ),
        migrations.AddField(
            model_name='immunization',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity of vaccine per animal per day (ml or mg)', max_digits=5),
        ),
        migrations.DeleteModel(
            name='ImmunizationRecord',
        ),
    ]
